### ISSUE TITLE
As a user I want to disable/enable mappings

### ISSUE THREAD

**Issue by nerdbeere** [uxebu/james#19]
Currently when I want to disable an existing mapping I need to delete it. As a user I want a button that lets me disable and reenable specific mappings.

**Comment by mitchhentges** [comment]
Ah, this can be closed, there's a neat-o switch that allows live enabling/disabling.
![mappingtoggle](https://cloud.githubusercontent.com/assets/7784737/12490936/8e73a04c-c078-11e5-93bf-c3ffb9af58e4.png)
