### ISSUE TITLE
NPM scripts don't run on windows

### ISSUE THREAD

**Issue by mitchhentges** [uxebu/james#20]
It would be convenient if the `npm` scripts didn't depend on *nix specific commands, like `rm`, etc

**Comment by nerdbeere** [comment]
That's true, we should use node packages like `rimraf` and `mkdirp` to ensure cross-platform support

**Comment by nerdbeere** [comment]
With [this PR](https://github.com/uxebu/james/pull/22) it should atleast build on windows
