### ISSUE TITLE
[Non-OSX] Items in top-bar menus simply error out

### ISSUE THREAD

**Issue by mitchhentges** [uxebu/james#21]
This includes any item under `James`, `Edit`, or `Window`
For example, upon clicking `James`>`About James`, the following window pops into the foreground:
![error](https://cloud.githubusercontent.com/assets/7784737/10977583/c7e8ba7e-83a6-11e5-84f6-0477c2c60ebf.png)

**Comment by nerdbeere** [comment]
Thanks for your feedback.

**Comment by mitchhentges** [comment]
This just in: this happens on Linux, too. I don't really know what I can describe about my environment that's relevant. Chrome version?

**Comment by mitchhentges** [comment]
So, this issue seems to be because [`selector` in menu items is OSX-only](https://github.com/atom/electron/issues/2268). That's no fun :(
