### ISSUE TITLE
James doesn't show any requests using Firefox 

### ISSUE THREAD

**Issue by davidneat** [uxebu/james#26]
issue needs evaluation

**Comment by mitchhentges** [comment]
I'd be totally down to take a look at this, but it's working 100% awesomely for me:
* Arch Linux
* Firefox `43.0.1`

What are you running? Perhaps I can try to reproduce it

**Comment by mitchhentges** [comment]
@davidneat @nerdbeere can this be closed?

**Comment by nerdbeere** [comment]
This is working perfectly fine.
