### ISSUE TITLE
`npm lint` doesn't run on Travis

### ISSUE THREAD

**Issue by mitchhentges** [uxebu/james#32]
When looking at the [log for the last successful](https://s3.amazonaws.com/archive.travis-ci.org/jobs/103650204/log.txt) master build, it looks like `npm run lint` never occurs.

**Comment by nerdbeere** [comment]
This is still an issue, right?
Travis currently doesn't run the lint script

**Comment by mitchhentges** [comment]
Derp, closed the wrong one of mine, sorry
