### ISSUE TITLE
Show available browsers when James is launched

### ISSUE THREAD

**Issue by mitchhentges** [uxebu/james#35]
Right now, Chrome and Firefox are always shown, regardless of whether they are installed, or if other browsers are available.

Instead, `browser-launcher2`'s [detection feature](https://github.com/benderjs/browser-launcher2#browser-detection) should be used to find potential browsers

**Comment by nerdbeere** [comment]
That's an idea we had some time ago: https://github.com/uxebu/james/issues/9
As you explained this a lot better, I'm gonna close #9

**Comment by mitchhentges** [comment]
Oh, I thought #9 was strictly about using the other library. I was working on that when I had the idea about detection :wink:
