### ISSUE TITLE
Add HTTPs Support

### ISSUE THREAD

**Issue by nerdbeere** [uxebu/james#5]
Currently James doesn't have HTTPs support.
The reason is, that hoxy, which is the underlying proxy used in James, currently doesn't support HTTPs. This feature is under heavy discussion and can be followed here: https://github.com/greim/hoxy/issues/4

**Comment by nerdbeere** [comment]
I got SSL support working on my machine. But currently all the certificate stuff is a lot of manual labor.
I need to figure out a way to automatically add certificates to the keychain.

**Comment by mitchhentges** [comment]
Ayy, should be solved by #28

**Comment by mitchhentges** [comment]
So, though certs and stuff can't be added to the keychain, can this be closed? Perhaps new issues can be created for GUI path-to-key selection, auto-generation, etc

**Comment by nerdbeere** [comment]
Yeah, that makes sense.
